services:
  api:
    build: .
    container_name: shortener_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    # A condição 'service_healthy' é crucial para evitar a condição de corrida na inicialização.

    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      
    # O healthcheck verifica se o MySQL está pronto para aceitar conexões antes de iniciar a API.

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ../url-shortener-frontend
      dockerfile: Dockerfile
    container_name: shortener_ui
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  mysql_data: